//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugLocalizationHybridApproach.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugLocalizationHybridApproach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;24&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.5471698113207548&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;59&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;18.553459119496857&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;76&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;23.89937106918239&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;40.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_JSM_JSM {
            get {
                return ResourceManager.GetString("AspectJ_JSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;23&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.232704402515723&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;47&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;14.779874213836479&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;70&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.0125786163522&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;38.761 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_JSM_LSI {
            get {
                return ResourceManager.GetString("AspectJ_JSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;50&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;15.723270440251572&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;112&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;35.220125786163521&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;144&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45.283018867924525&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_JSM_PMI {
            get {
                return ResourceManager.GetString("AspectJ_JSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;18&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;5.6603773584905657&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;51&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;16.037735849056602&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;72&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.641509433962263&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;36. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_JSM_VSM {
            get {
                return ResourceManager.GetString("AspectJ_JSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;25&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.8616352201257858&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;59&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;18.553459119496857&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;76&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;23.89937106918239&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;41.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_LSI_JSM {
            get {
                return ResourceManager.GetString("AspectJ_LSI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;24&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.5471698113207548&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;47&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;14.779874213836479&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;70&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.0125786163522&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;39.42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_LSI_LSI {
            get {
                return ResourceManager.GetString("AspectJ_LSI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;51&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;16.037735849056602&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;112&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;35.220125786163521&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;144&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45.283018867924525&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_LSI_PMI {
            get {
                return ResourceManager.GetString("AspectJ_LSI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;19&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;5.9748427672955975&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;51&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;16.037735849056602&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;72&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.641509433962263&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;37. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_LSI_VSM {
            get {
                return ResourceManager.GetString("AspectJ_LSI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;24&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.5471698113207548&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;59&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;18.553459119496857&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;76&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;23.89937106918239&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;40.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_PMI_JSM {
            get {
                return ResourceManager.GetString("AspectJ_PMI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;23&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.232704402515723&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;47&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;14.779874213836479&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;70&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.0125786163522&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;38.766 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_PMI_LSI {
            get {
                return ResourceManager.GetString("AspectJ_PMI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;50&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;15.723270440251572&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;112&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;35.220125786163521&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;144&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45.283018867924525&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_PMI_PMI {
            get {
                return ResourceManager.GetString("AspectJ_PMI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;18&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;5.6603773584905657&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;51&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;16.037735849056602&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;72&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.641509433962263&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;36. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_PMI_VSM {
            get {
                return ResourceManager.GetString("AspectJ_PMI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;24&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.5471698113207548&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;59&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;18.553459119496857&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;76&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;23.89937106918239&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;40.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_VSM_JSM {
            get {
                return ResourceManager.GetString("AspectJ_VSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;23&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;7.232704402515723&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;47&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;14.779874213836479&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;70&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.0125786163522&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;38.762 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_VSM_LSI {
            get {
                return ResourceManager.GetString("AspectJ_VSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;50&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;15.723270440251572&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;112&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;35.220125786163521&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;144&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45.283018867924525&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_VSM_PMI {
            get {
                return ResourceManager.GetString("AspectJ_VSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;18&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;5.6603773584905657&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;51&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;16.037735849056602&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;72&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;22.641509433962263&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;36. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AspectJ_VSM_VSM {
            get {
                return ResourceManager.GetString("AspectJ_VSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;438&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;14.243902439024391&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;922&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.983739837398375&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1192&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;38.764227642276424&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_JSM_JSM {
            get {
                return ResourceManager.GetString("Eclipse_JSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;564&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.341463414634145&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1043&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;33.918699186991873&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1306&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;42.471544715447152&lt;/Top10Percent&gt;
        ///        &lt;SumR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_JSM_LSI {
            get {
                return ResourceManager.GetString("Eclipse_JSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;541&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;17.59349593495935&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1240&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40.325203252032523&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1588&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;51.642276422764226&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_JSM_PMI {
            get {
                return ResourceManager.GetString("Eclipse_JSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;272&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.845528455284553&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;662&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;21.528455284552845&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;900&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;29.26829268292683&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;47 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_JSM_VSM {
            get {
                return ResourceManager.GetString("Eclipse_JSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;438&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;14.243902439024391&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;922&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.983739837398375&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1192&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;38.764227642276424&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_LSI_JSM {
            get {
                return ResourceManager.GetString("Eclipse_LSI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;564&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.341463414634145&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1043&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;33.918699186991873&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1306&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;42.471544715447152&lt;/Top10Percent&gt;
        ///        &lt;SumR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_LSI_LSI {
            get {
                return ResourceManager.GetString("Eclipse_LSI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;541&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;17.59349593495935&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1240&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40.325203252032523&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1588&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;51.642276422764226&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_LSI_PMI {
            get {
                return ResourceManager.GetString("Eclipse_LSI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;272&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.845528455284553&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;662&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;21.528455284552845&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;900&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;29.26829268292683&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;47 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_LSI_VSM {
            get {
                return ResourceManager.GetString("Eclipse_LSI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;439&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;14.276422764227643&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;922&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.983739837398375&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1192&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;38.764227642276424&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_PMI_JSM {
            get {
                return ResourceManager.GetString("Eclipse_PMI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;564&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.341463414634145&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1043&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;33.918699186991873&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1306&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;42.471544715447152&lt;/Top10Percent&gt;
        ///        &lt;SumR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_PMI_LSI {
            get {
                return ResourceManager.GetString("Eclipse_PMI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;541&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;17.59349593495935&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1241&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40.357723577235774&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1589&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;51.674796747967477&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_PMI_PMI {
            get {
                return ResourceManager.GetString("Eclipse_PMI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;273&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.8780487804878057&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;662&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;21.528455284552845&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;900&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;29.26829268292683&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_PMI_VSM {
            get {
                return ResourceManager.GetString("Eclipse_PMI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;439&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;14.276422764227643&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;922&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.983739837398375&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1192&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;38.764227642276424&lt;/Top10Percent&gt;
        ///        &lt;SumRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_VSM_JSM {
            get {
                return ResourceManager.GetString("Eclipse_VSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;564&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.341463414634145&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1043&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;33.918699186991873&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1306&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;42.471544715447152&lt;/Top10Percent&gt;
        ///        &lt;SumR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_VSM_LSI {
            get {
                return ResourceManager.GetString("Eclipse_VSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;540&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;17.5609756097561&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;1241&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40.357723577235774&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;1589&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;51.674796747967477&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_VSM_PMI {
            get {
                return ResourceManager.GetString("Eclipse_VSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;272&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.845528455284553&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;662&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;21.528455284552845&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;900&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;29.26829268292683&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;47 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eclipse_VSM_VSM {
            get {
                return ResourceManager.GetString("Eclipse_VSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;25&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;58.139534883720927&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;31&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;72.093023255813947&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;20.32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_JSM_JSM {
            get {
                return ResourceManager.GetString("JodaTime_JSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;23&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;53.488372093023258&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;27&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;62.7906976744186&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;19.2998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_JSM_LSI {
            get {
                return ResourceManager.GetString("JodaTime_JSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.6046511627907&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;27&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;62.7906976744186&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;36&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;83.720930232558146&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;17.09505 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_JSM_PMI {
            get {
                return ResourceManager.GetString("JodaTime_JSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;9&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;20.930232558139537&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;22&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;51.162790697674417&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;29&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;67.441860465116278&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;15.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_JSM_VSM {
            get {
                return ResourceManager.GetString("JodaTime_JSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;25&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;58.139534883720927&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;31&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;72.093023255813947&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;20.32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_LSI_JSM {
            get {
                return ResourceManager.GetString("JodaTime_LSI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;23&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;53.488372093023258&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;27&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;62.7906976744186&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;19.2998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_LSI_LSI {
            get {
                return ResourceManager.GetString("JodaTime_LSI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.6046511627907&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;27&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;62.7906976744186&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;36&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;83.720930232558146&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;17.09505 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_LSI_PMI {
            get {
                return ResourceManager.GetString("JodaTime_LSI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;9&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;20.930232558139537&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;22&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;51.162790697674417&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;29&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;67.441860465116278&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;15.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_LSI_VSM {
            get {
                return ResourceManager.GetString("JodaTime_LSI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;25&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;58.139534883720927&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;31&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;72.093023255813947&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;20.32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_PMI_JSM {
            get {
                return ResourceManager.GetString("JodaTime_PMI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;23&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;53.488372093023258&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;27&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;62.7906976744186&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;19.2998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_PMI_LSI {
            get {
                return ResourceManager.GetString("JodaTime_PMI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.6046511627907&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;27&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;62.7906976744186&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;36&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;83.720930232558146&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;17.09505 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_PMI_PMI {
            get {
                return ResourceManager.GetString("JodaTime_PMI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;9&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;20.930232558139537&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;22&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;51.162790697674417&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;29&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;67.441860465116278&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;15.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_PMI_VSM {
            get {
                return ResourceManager.GetString("JodaTime_PMI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;25&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;58.139534883720927&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;31&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;72.093023255813947&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;20.32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_VSM_JSM {
            get {
                return ResourceManager.GetString("JodaTime_VSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;16&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;37.2093023255814&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;23&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;53.488372093023258&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;27&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;62.7906976744186&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;19.2998 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_VSM_LSI {
            get {
                return ResourceManager.GetString("JodaTime_VSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;18.6046511627907&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;27&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;62.7906976744186&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;36&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;83.720930232558146&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;17.09505 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_VSM_PMI {
            get {
                return ResourceManager.GetString("JodaTime_VSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;9&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;20.930232558139537&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;22&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;51.162790697674417&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;29&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;67.441860465116278&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;15.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JodaTime_VSM_VSM {
            get {
                return ResourceManager.GetString("JodaTime_VSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;29&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.591836734693878&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;43&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;43.877551020408163&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;21. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_JSM_JSM {
            get {
                return ResourceManager.GetString("SWT_JSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.16326530612245&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;19&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;19.387755102040817&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;24&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;24.489795918367346&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;14.156 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_JSM_LSI {
            get {
                return ResourceManager.GetString("SWT_JSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;27&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;27.551020408163264&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;67&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;68.367346938775512&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;80&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;81.632653061224488&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;42. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_JSM_PMI {
            get {
                return ResourceManager.GetString("SWT_JSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;34&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;34.693877551020407&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;46&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;46.938775510204081&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;22. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_JSM_VSM {
            get {
                return ResourceManager.GetString("SWT_JSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;29&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.591836734693878&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;43&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;43.877551020408163&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;21. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_LSI_JSM {
            get {
                return ResourceManager.GetString("SWT_LSI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.16326530612245&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;19&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;19.387755102040817&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;24&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;24.489795918367346&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;14.156 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_LSI_LSI {
            get {
                return ResourceManager.GetString("SWT_LSI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;27&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;27.551020408163264&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;67&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;68.367346938775512&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;80&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;81.632653061224488&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;42. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_LSI_PMI {
            get {
                return ResourceManager.GetString("SWT_LSI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;34&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;34.693877551020407&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;46&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;46.938775510204081&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;22. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_LSI_VSM {
            get {
                return ResourceManager.GetString("SWT_LSI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;29&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.591836734693878&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;43&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;43.877551020408163&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;21. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_PMI_JSM {
            get {
                return ResourceManager.GetString("SWT_PMI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.16326530612245&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;19&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;19.387755102040817&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;24&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;24.489795918367346&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;14.156 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_PMI_LSI {
            get {
                return ResourceManager.GetString("SWT_PMI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;27&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;27.551020408163264&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;67&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;68.367346938775512&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;80&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;81.632653061224488&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;42. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_PMI_PMI {
            get {
                return ResourceManager.GetString("SWT_PMI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;34&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;34.693877551020407&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;46&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;46.938775510204081&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;22. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_PMI_VSM {
            get {
                return ResourceManager.GetString("SWT_PMI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;29&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;29.591836734693878&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;43&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;43.877551020408163&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;21. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_VSM_JSM {
            get {
                return ResourceManager.GetString("SWT_VSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;8&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;8.16326530612245&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;19&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;19.387755102040817&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;24&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;24.489795918367346&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;14.156 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_VSM_LSI {
            get {
                return ResourceManager.GetString("SWT_VSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;27&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;27.551020408163264&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;67&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;68.367346938775512&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;80&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;81.632653061224488&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;42. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_VSM_PMI {
            get {
                return ResourceManager.GetString("SWT_VSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;11&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;11.224489795918368&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;34&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;34.693877551020407&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;46&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;46.938775510204081&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;22. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWT_VSM_VSM {
            get {
                return ResourceManager.GetString("SWT_VSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;7&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;35&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;11&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;55&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;13&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;65&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8.7319791255879124&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.436598956 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_JSM_JSM {
            get {
                return ResourceManager.GetString("ZXing_JSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;9&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.6207194195240726&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.38103597097 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_JSM_LSI {
            get {
                return ResourceManager.GetString("ZXing_JSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;5&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;25&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;6.8301092094108915&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3415054604 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_JSM_PMI {
            get {
                return ResourceManager.GetString("ZXing_JSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;8&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.3614377782555449&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3680718889 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_JSM_VSM {
            get {
                return ResourceManager.GetString("ZXing_JSM_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;7&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;35&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;11&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;55&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;13&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;65&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8.7319791255879124&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.436598956 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_LSI_JSM {
            get {
                return ResourceManager.GetString("ZXing_LSI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;9&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.6207194195240726&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.38103597097 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_LSI_LSI {
            get {
                return ResourceManager.GetString("ZXing_LSI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;5&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;25&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;6.8301092094108915&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3415054604 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_LSI_PMI {
            get {
                return ResourceManager.GetString("ZXing_LSI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;8&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.3625872035429012&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3681293601 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_LSI_VSM {
            get {
                return ResourceManager.GetString("ZXing_LSI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;7&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;35&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;11&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;55&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;13&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;65&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8.7319791255879124&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.436598956 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_PMI_JSM {
            get {
                return ResourceManager.GetString("ZXing_PMI_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;9&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.6207194195240726&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.38103597097 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_PMI_LSI {
            get {
                return ResourceManager.GetString("ZXing_PMI_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;5&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;25&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;6.8301092094108915&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3415054604 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_PMI_PMI {
            get {
                return ResourceManager.GetString("ZXing_PMI_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;8&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.3614377782555449&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3680718889 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_PMI_VSM {
            get {
                return ResourceManager.GetString("ZXing_PMI_VSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;7&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;35&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;11&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;55&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;13&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;65&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;8.7319791255879124&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.436598956 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_VSM_JSM {
            get {
                return ResourceManager.GetString("ZXing_VSM_JSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;9&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;45&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.6207194195240726&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.38103597097 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_VSM_LSI {
            get {
                return ResourceManager.GetString("ZXing_VSM_LSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;5&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;25&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;9&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;45&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;6.8301092094108915&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3415054604 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_VSM_PMI {
            get {
                return ResourceManager.GetString("ZXing_VSM_PMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProcessorListResult xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Results&gt;
        ///    &lt;ProcessorResultKeyValue&gt;
        ///      &lt;Key&gt;0&lt;/Key&gt;
        ///      &lt;Result&gt;
        ///        &lt;Top01&gt;6&lt;/Top01&gt;
        ///        &lt;Top01Percent&gt;30&lt;/Top01Percent&gt;
        ///        &lt;Top05&gt;8&lt;/Top05&gt;
        ///        &lt;Top05Percent&gt;40&lt;/Top05Percent&gt;
        ///        &lt;Top10&gt;11&lt;/Top10&gt;
        ///        &lt;Top10Percent&gt;55&lt;/Top10Percent&gt;
        ///        &lt;SumRr&gt;7.3625872035429012&lt;/SumRr&gt;
        ///        &lt;Mrr&gt;0.3681293601 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZXing_VSM_VSM {
            get {
                return ResourceManager.GetString("ZXing_VSM_VSM", resourceCulture);
            }
        }
    }
}
